### ISSUE TITLE
Cannot open Prototype Token with creatures using MM sheet

### ISSUE THREAD

**Issue by bklick** [giffyglyph/foundry_5e_monster_maker#17] opened 2021-06-01 13:19 UTC
Trying to open a creature's prototype token causes the following error message:

![image](https://user-images.githubusercontent.com/3947702/120329959-f7f59980-c2b1-11eb-9884-51397d5ffa78.png)

**Comment by giffyglyph** [comment] 2021-06-02 19:24
@bklick I can't seem to replicate this; can you upgrade to the latest development version and try again? Thanks!

**Comment by giffyglyph** [comment] 2021-06-03 13:01
This is caused by a reference to a potentially-invalid CombatTrackerConfig function.

> const attributes = Object.values(CombatTrackerConfig.prototype.getAttributeChoices())[0]; // Bit of a hack

![image](https://user-images.githubusercontent.com/42981044/120648879-0a1f3580-c474-11eb-9caa-6600fceef549.png)

This has been updated in 8.6, so will backport the fix into GMM.

**Comment by giffyglyph** [comment] 2021-06-05 02:16
Reference to invalid CombatTrackerConfig replaced with 8.6 code. Verified in v0.5.5-dev; closing.

**Closed by giffyglyph** 2021-06-05 02:16 UTC
Labels: bug
