### ISSUE TITLE
Monster Maker sheet seems to prevent character sheet ability scores, exp from being changed.

### ISSUE THREAD

**Issue by bklick** [giffyglyph/foundry_5e_monster_maker#27] opened 2021-06-04 00:18 UTC
I am trying to better isolate what is causing this, so when I know more I'll update? Hopefully this is some kind of PEBKAC, but MM is the only module currently active.

![image](https://user-images.githubusercontent.com/3947702/120727522-5ed8a580-c4a0-11eb-88ea-834fb0f46ceb.png)

**Comment by giffyglyph** [comment] 2021-06-04 00:46
The issue is in the refresh code; the MM checks to see if the current actor sheet _or default sheet_ is the MM sheet. But we should only be doing this for npcs.

**Comment by bklick** [comment] 2021-06-05 02:07
Let me know if I can help test it.

**Comment by giffyglyph** [comment] 2021-06-05 02:13
Monster sheet now affects only npc sheets. Verified in v0.5.5-dev. Closing.

**Closed by giffyglyph** 2021-06-05 02:13 UTC
Labels: bug
