### ISSUE TITLE
MM sheet creatures cannot roll initiative from combat tracker

### ISSUE THREAD

**Issue by bklick** [giffyglyph/foundry_5e_monster_maker#16] opened 2021-06-01 13:13 UTC
When trying to roll initiative for creatures with the MM sheet, nothing happens. 

![image](https://user-images.githubusercontent.com/3947702/120328961-fb3c5580-c2b0-11eb-8c32-78bc1746c5d2.png)

This is especially confounding to general use since the DM will probably be rolling all monster initiatives at the same time with the Roll NPCs feature.

**Comment by giffyglyph** [comment] 2021-06-02 17:24
This is a duplicate of [#14] and will be resolved by that fix; closing.

**Closed by giffyglyph** 2021-06-02 17:24 UTC
